FROM python:3.12

RUN apt-get update && apt-get install -y --no-install-recommends \
    git \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir \
    dbt-core \
    dbt-clickhouse

WORKDIR /usr/app/dbt

COPY ../../dbt_project /usr/app/dbt

ENV DBT_PROFILES_DIR=/usr/app/dbt

CMD ["dbt", "--version"]