version: 2

models:
  - name: raw
    description: "External tables from MinIO"
    
    data_tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - ticker_symbol
            - ingested_date

    columns:
      - name: ticker_symbol
        description: "Mã chứng khoán"
        data_tests:
          - not_null

      - name: ingested_date
        description: "Ngày nạp dữ liệu"
        data_tests:
          - not_null