import os
from dotenv import load_dotenv, find_dotenv

find_dotenv() 
load_dotenv()


AIRFLOW_UID=os.get("AIRFLOW_UID")

_AIRFLOW_WWW_USER_USERNAME=os.getenv("_AIRFLOW_WWW_USER_USERNAME")
_AIRFLOW_WWW_USER_PASSWORD=os.getenv("_AIRFLOW_WWW_USER_PASSWORD")
TIMEZONE="Asia/Ho_Chi_Minh"

MINIO_ACCESS_KEY=os.getenv("MINIO_ACCESS_KEY")
MINIO_SECRET_KEY=os.getenv("MINIO_SECRET_KEY")
MINIO_ENDPOINT=os.getenv("MINIO_ENDPOINT")
AIRFLOW_CONN_MINIO_CONN=os.getenv("AIRFLOW_CONN_MINIO_CONN")

CLICKHOUSE_USER=os.getenv("CLICKHOUSE_USER")
CLICKHOUSE_PASSWORD=os.getenv("CLICKHOUSE_PASSWORD")
CLICKHOUSE_DB=os.getenv("CLICKHOUSE_DB")
